In [56]:
import pandas as pd
import numpy as np
import random as rnd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [3]:
train_df = pd.read_csv('data/train_altered.csv')
test_df = pd.read_csv('data/test_altered.csv')
X_train = train_df.drop("Survived", axis=1)
Y_train = train_df["Survived"]
X_test  = test_df.drop("PassengerId", axis=1).copy()
X_train.shape, Y_train.shape, X_test.shape

((891, 9), (891,), (418, 9))

In [57]:
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
acc_log

80.36

In [5]:
coeff_df = pd.DataFrame(train_df.columns.delete(0))
coeff_df.columns = ['Feature']
coeff_df["Correlation"] = pd.Series(logreg.coef_[0])

coeff_df.sort_values(by='Correlation', ascending=False)

Feature  Correlation
2        Sex     2.201768
6      Title     0.397974
3        Age     0.287277
5   Embarked     0.263101
7    IsAlone     0.128674
0   Survived     0.000020
4       Fare    -0.085247
8  Age*Class    -0.311319
1     Pclass    -0.749008

In [62]:
svc = SVC()
msk = np.random.rand(len(X_train)) < 0.8
svc.fit(X_train[msk], Y_train[msk])
#Y_pred = svc.predict(X_test)
scores = cross_val_score(svc, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
acc_svc = round(svc.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_svc)

Cross Validation Accuracy:
[0.61971831 0.57042254 0.62411348 0.59285714 0.62142857]
Test Accuracy:
62.9


In [60]:
knn = KNeighborsClassifier(n_neighbors = 3)
msk = np.random.rand(len(X_train)) < 0.8
knn.fit(X_train[msk], Y_train[msk])
#Y_pred = knn.predict(X_test)
scores = cross_val_score(gaussian, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
acc_knn = round(knn.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_knn)


Cross Validation Accuracy:
[0.68531469 0.70422535 0.75177305 0.4964539  0.76595745]
Test Accuracy:
61.2


In [59]:
gaussian = GaussianNB()
msk = np.random.rand(len(X_train)) < 0.8
gaussian.fit(X_train[msk], Y_train[msk])
#Y_pred = gaussian.predict(X_test)
scores = cross_val_score(gaussian, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
acc_gaussian = round(gaussian.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_gaussian)

Cross Validation Accuracy:
[0.70547945 0.69178082 0.75342466 0.57534247 0.78472222]
Test Accuracy:
71.78


In [58]:
perceptron = Perceptron()
msk = np.random.rand(len(X_train)) < 0.8
perceptron.fit(X_train[msk], Y_train[msk])
scores = cross_val_score(perceptron, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
#Y_pred = perceptron.predict(X_test)
acc_perceptron = round(perceptron.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_perceptron)


Cross Validation Accuracy:
[0.40425532 0.38297872 0.37588652 0.37857143 0.62589928]
Test Accuracy:
59.26


In [64]:
linear_svc = LinearSVC()
msk = np.random.rand(len(X_train)) < 0.8
linear_svc.fit(X_train[msk], Y_train[msk])
#Y_pred = linear_svc.predict(X_test)
scores = cross_val_score(linear_svc, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
acc_linear_svc = round(linear_svc.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_linear_svc)

Cross Validation Accuracy:
[0.70138889 0.8125     0.67361111 0.38194444 0.38732394]
Test Accuracy:
54.34


In [65]:
sgd = SGDClassifier()
msk = np.random.rand(len(X_train)) < 0.8
sgd.fit(X_train[msk], Y_train[msk])
#Y_pred = sgd.predict(X_test)
scores = cross_val_score(sgd, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
acc_sgd = round(sgd.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_sgd)


Cross Validation Accuracy:
[0.6137931  0.60689655 0.39310345 0.39310345 0.60839161]
Test Accuracy:
65.48


In [68]:
decision_tree = DecisionTreeClassifier()
msk = np.random.rand(len(X_train)) < 0.8
decision_tree.fit(X_train[msk], Y_train[msk])
#Y_pred = decision_tree.predict(X_train[~msk])
scores = cross_val_score(decision_tree, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
acc_decision_tree = round(decision_tree.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_decision_tree)


Cross Validation Accuracy:
[0.82312925 0.69863014 0.7862069  0.77241379 0.80689655]
Test Accuracy:
77.3


In [71]:
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, Y_train)
#Y_pred = random_forest.predict(X_test)
scores = cross_val_score(random_forest, X_train[msk], Y_train[msk], cv=5)
print("Cross Validation Accuracy:")
print(scores)
random_forest.score(X_train, Y_train)
acc_random_forest = round(random_forest.score(X_train[~msk], Y_train[~msk]) * 100, 2)
print("Test Accuracy:")
print(acc_random_forest)

Cross Validation Accuracy:
[0.75510204 0.82876712 0.80689655 0.8        0.80689655]
Test Accuracy:
100.0


In [72]:
models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree]})
models.sort_values(by='Score', ascending=False)



Model   Score
3               Random Forest  100.00
2         Logistic Regression   80.36
8               Decision Tree   77.30
4                 Naive Bayes   71.78
6  Stochastic Gradient Decent   65.48
0     Support Vector Machines   62.90
1                         KNN   61.20
5                  Perceptron   59.26
7                  Linear SVC   54.34